name: HACS Action

on:
  push:
    tags:
      - "*"

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Faster HACS Action
        uses: hacs/action@22.5.0
        with:
          category: integration
